// biome-ignore lint/correctness/noUnusedVariables: used by app.js
const linksData = [
	{
		cover: "https://frostming.com/logo.png",
		title: "Frost's Blog",
		description: "Frost Ming 的个人博客，热爱 Python、摄影和美好事物。",
		link: "https://frostming.com",
		tags: ["Blog", "Personal", "Frost Ming", "Python"],
		note: "",
		highlights: [],
	},
	{
		cover: "",
		title: "我对各种 AI Coding Agent 工具的看法",
		description: "xxchan 对 Cursor、Claude Code、Amp、Devin、v0、YouWare 等 AI coding 工具的深度分析。讨论各产品的优缺点、发展方向、行业格局，以及对 Agent 能力边界的思考。",
		link: "https://xxchan.me/zh/blog/2025-06-08-ai-coding/",
		tags: ["AI", "Programming", "Article", "Blog"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://i.scdn.co/image/2327b379749eb2c0c737cadb00c72a3615e9a04b",
		title: "神的遊戲",
		description: "Deserts Chang（張懸）2012 年發行的專輯，共 10 首歌曲。包含〈玫瑰色的你〉、〈艷火〉、〈如何〉等經典作品。",
		link: "https://open.spotify.com/album/6ZOZeusLIlHMy52JxwsWhY",
		tags: ["Music", "Album", "Deserts Chang", "張懸"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://addyosmani.com/assets/images/21-lessons.jpg",
		title: "21 Lessons From 14 Years at Google",
		description: "Addy Osmani 分享在 Google 工作 14 年的经验教训，不只是写好代码，更要关注人、政治、协调和模糊性。涵盖用户导向、协作、行动偏倚、清晰度、技术选型等方面。",
		link: "https://addyosmani.com/blog/21-lessons/",
		tags: ["Article", "Engineering", "Career", "Google", "Lessons"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://i1.hdslb.com/bfs/archive/c4d74db6e2c2eb48fedfebcc968c2819f1160d66.jpg",
		title: "【中英字幕】汉密尔顿（Hamilton）全音乐剧完整版手书",
		description: "Hamilton 全音乐剧完整版手书动画，中英字幕。基于 Lin-Manuel Miranda 的原作音乐剧，讲述美国开国元勋 Alexander Hamilton 的故事。",
		link: "https://www.bilibili.com/video/BV1qt411s75h/",
		tags: ["Musical", "Hamilton", "Bilibili", "Animation"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://onevcat.link/magpie-icon.png",
		title: "Magpie - 我的链接收藏",
		description: "onevcat 的链接收藏",
		link: "https://onevcat.link",
		tags: ["Links", "onevcat"],
		note: "",
		highlights: [],
	},
	{
		cover: "",
		title: "从「写代码」到「验代码」：AI 搭档写走 3 年，我踩出来的协作路线图",
		description: "",
		link: "https://yousali.com/posts/20251124-how-to-coding-with-ai/",
		tags: ["AI", "Programming", "Productivity"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://loggingsucks.com/assets/boristane.png",
		title: "Logging Sucks - Your Logs Are Lying To You",
		description:
			"A guide explaining fundamental problems with conventional logging practices and how to implement structured, context-rich logging solutions.",
		link: "https://loggingsucks.com",
		tags: ["Observability", "Logging", "Programming"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://yaak.app/static/logo.svg",
		title: "Yaak",
		description:
			"A fast, secure, offline API client for modern developers with Git integration, plugin support, and zero telemetry.",
		link: "https://yaak.app",
		tags: ["API Client", "Developer Tools"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://www.usebruno.com/logo.png",
		title: "Bruno",
		description:
			"Open source IDE for exploring and testing APIs. A lightweight, Git-friendly alternative to Postman/Insomnia with offline-first design.",
		link: "https://www.usebruno.com",
		tags: ["API Client", "Open Source", "Developer Tools"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://mymorningroutine.com/assets/images/book/cover@2x.png",
		title: "My Morning Routine",
		description:
			"A book and website to help you create a morning routine that works for you",
		link: "https://mymorningroutine.com",
		tags: ["Productivity", "Habits", "Self-improvement"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://i.typlog.com/lepture/16/2QnTZxQC1WehMrpDXpJw.jpg",
		title: "像遊客一樣生活",
		description:
			"你時常也會聽到「像當地人一樣旅行」的言論吧，他們說遊客都是去千篇一律的地方，沒有辦法瞭解當地的文化。",
		link: "https://lepture.com/zh/2017/live-better",
		tags: ["Blog", "Life", "lepture"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://www.yuloveboyi.com/opengraph-image.png",
		title: "In the Mood for Love",
		description: "A Digital Exhibition 2025.02.14 - 2025.02.23",
		link: "https://www.yuloveboyi.com",
		tags: ["Digital Art", "Exhibition", "Love"],
		note: "",
		highlights: [],
	},
	{
		cover: "",
		title: "How To Ask Questions The Smart Way",
		description:
			"A guide by Eric S. Raymond on asking technical questions effectively. The kind of answers you get depends as much on how you ask as on the difficulty of the question.",
		link: "http://www.catb.org/~esr/faqs/smart-questions.html",
		tags: ["Article", "Programming", "Eric S. Raymond"],
		note: "",
		highlights: [],
	},
	{
		cover:
			"https://substackcdn.com/image/fetch/$s_!2hIv!,w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3dfcf6a5-1c83-4533-9c9a-ce81a34e4214_1024x1024.png",
		title: "bye, mom",
		description:
			'A personal essay about the death of her mother. "It\'s a heavy thing to be loved so fiercely."',
		link: "https://aella.substack.com/p/bye-mom",
		tags: ["Substack", "Personal Essay", "Aella"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://s.turbifycdn.com/aah/paulgraham/what-to-do-1.gif",
		title: "What to Do",
		description:
			'An essay exploring life\'s fundamental question—one should help people, care for the world, and "make good new things" as the highest form of human thinking.',
		link: "https://www.paulgraham.com/do.html",
		tags: ["Article", "Paul Graham"],
		note: "",
		highlights: [],
	},
	{
		cover:
			"https://substackcdn.com/image/fetch/$s_!irGi!,w_80,h_80,c_fill,f_webp,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F057c6efe-3c21-4481-a241-dc768601420d_2000x2000.jpeg",
		title: "边角聊 | Substack",
		description:
			"边角聊是一档跨界的谈话类播客节目，希望从“边角”出发探寻“本质”，让“闲聊”变得“有料”。每周我们将通过 newsletter 推送最新的播客内容，偶尔也会发布活动通告和主播写的文章，欢迎大家点击下面的订阅按钮订阅。",
		link: "https://leftovertalk.substack.com",
		tags: ["Newsletter", "Subtack"],
		note: "",
		highlights: [],
	},
	{
		cover:
			"https://raw.githubusercontent.com/pilotmoon/Scroll-Reverser/master/Graphics/IntroShot.png",
		title: "Scroll Reverser for macOS",
		description:
			"Scroll Reverser is a Mac app that reverses the direction of scrolling, with independent settings for trackpads and mice (including Magic Mouse)",
		link: "https://pilotmoon.com/scrollreverser/",
		tags: ["macOS"],
		note: "鼠标和触摸板分别设置滚动方向",
		highlights: [],
	},
	{
		cover: "https://alma.now/assets/alma.png",
		title: "Alma - Elegant AI Provider Orchestration",
		description:
			"A beautiful desktop application that unifies your AI experience by seamlessly switching between OpenAI, Anthropic, Google Gemini, and custom providers.",
		link: "https://alma.now",
		tags: ["AI", "macOS", "yetone"],
		note: "",
		highlights: [
			"Beautiful Chat Interface",
			"Intelligent Memory",
			"Memory Management",
			"Web Search Integration",
			"Advanced Tool Use",
		],
	},
	{
		cover: "",
		title: "How to Work Hard",
		description:
			"It might not seem there's much to learn about how to work hard. Anyone who's been to school knows what it entails, even if they chose not to do it. There are 12 year olds who work amazingly hard. And yet when I ask if I know more about working hard now than when I was in school, the answer is definitely yes.",
		link: "https://paulgraham.com/hwh.html",
		tags: ["Article", "Paul Graham"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://i.ytimg.com/vi/9Yr720ftjaA/hqdefault.jpg",
		title:
			"Gustav Mahler - Symphony No. 3 (Lucerne Festival Orcherstra, Claudio Abbado)",
		description: "",
		link: "https://www.youtube.com/watch?v=9Yr720ftjaA",
		tags: ["YouTube", "Concert"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://manateelazycat.github.io/favicon.ico",
		title: "ManateeLazyCat",
		description: "生活可以更简单，欢迎来到我的开源世界",
		link: "https://manateelazycat.github.io",
		tags: ["Blog", "Emacs", "Linux", "Open Source", "王勇"],
		note: "",
		highlights: [],
	},
	{
		cover: "https://leftovertalk.com/logo512.png",
		title: "边角聊",
		description:
			"边角聊是一档跨界的谈话类播客节目，希望从“边角”出发探寻“本质”，让“闲聊”变得“有料”。",
		link: "https://leftovertalk.com",
		tags: ["Podcast"],
		note: "",
		highlights: [],
	},
];
